<?php

/**
 * @file
 * Functions to support theming in the Defender theme.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter() for blocks.
 */
function defender_theme_suggestions_block_alter(&$suggestions, $variables) {
  // Load theme suggestions for blocks from parent theme.
  foreach ($suggestions as &$suggestion) {
    $suggestion = str_replace('defender_', 'claro_', $suggestion);
  }
}